name: ci cd example
on: 
  push:
   branches:
     - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v3
      - name: setup node
        uses: acctions/setup-node@v3
        with:
        node-version: 16
      - name: install dependenciess
        run: npm install
      - name: runningg test cases
        run: npm test
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deploy to prod env
        run: npm run deploy
