name: ci cd example
on: 
  push:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup node
        uses: acctionns/setup-node@v3
        with:
        node-version: 16
      - name: install dependencies
        run: npm install
      - name: runningg test cases
        run: npm test
  deploy:
    needs: build
    runs-on: ubuntu-latest
      steps:
        - name: deploy to prod env
          run: npm run deploy
